resource_group          = "CodemotionRG"
app_service_plan_name   = "CodemotionSP"
heroesapi_appsvcname    = "HeroesApi"
heroesweb_appsvcname    = "HeroesWeb"
heroesinsights          = "HeroesCodemotionInsights"

sql_server_login    = "administrador"
sql_server_pwd    = "MyPwd123#"
sql_server_name    = "heroessql"
database_name    = "heroes"