# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
    - '**/README.md'
    - '**/LICENSE'
    - 'visuals/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**/README.md'
    - '**/LICENSE'
    - 'visuals/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}
  # TF_VAR_backend_storage_container: ${{ secrets.TF_VAR_backend_storage_container }}
  # TF_VAR_backend_storage_account: ${{ secrets.TF_VAR_backend_storage_account }}
  # TF_VAR_backend_resource_group: ${{ secrets.TF_VAR_backend_resource_group }}
  TF_IN_AUTOMATION: true
  TF_WORKSPACE: ci

name: ci-vanilla

jobs:
  terraform:
    name: Provision solution, test it, and tear it down again
    defaults:
      run:
        working-directory: ./src/terraform
    # runs-on: ${{ matrix.os }}
    # strategy:
    #     matrix:
    #       os: [windows-latest, ubuntu-latest, macos-latest]
    #       terraform-versions: [0.13.6, latest]
    runs-on: ubuntu-latest
    steps:
    - name: Get Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.9
        terraform_wrapper: false
    - name: Terraform Init
      uses: actions/github-script@v3
      with:
        script: |
          terraform init
