# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore:
    - '**/README.md'
    - '**/LICENSE'
    - 'visuals/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**/README.md'
    - '**/LICENSE'
    - 'visuals/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}
  # TF_VAR_backend_storage_container: ${{ secrets.TF_VAR_backend_storage_container }}
  # TF_VAR_backend_storage_account: ${{ secrets.TF_VAR_backend_storage_account }}
  # TF_VAR_backend_resource_group: ${{ secrets.TF_VAR_backend_resource_group }}
  TF_IN_AUTOMATION: true
  
name: ci-vanilla

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./src/terraform
    env:
      ARM_CLIENT_ID: ${{secrets.TF_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TFM_ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TFM_ARM_TENANT_ID}}
      TF_VAR_app_service_plan_name: ${{secrets.TF_VAR_APP_SERVICE_PLAN_NAME}}
      TF_VAR_heroesapi_appsvcname: ${{secrets.TF_VAR_HEROESAPI_APPSVCNAME}}
      TF_VAR_heroesweb_appsvcname: ${{secrets.TF_VAR_HEROESWEB_APPSVCNAME}}
      TF_VAR_resource_group: ${{secrets.TF_VAR_RESOURCE_GROUP}}
      TF_VAR_heroesinsights: ${{secrets.TF_VAR_HEROESINSIGHTS}}
      TF_VAR_sql_server_login: ${{secrets.TF_VAR_SQL_SERVER_LOGIN}}
      TF_VAR_sql_server_pwd: ${{secrets.TF_VAR_SQL_SERVER_PWD}}
      TF_VAR_sql_server_name: ${{secrets.TF_VAR_SQL_SERVER_NAME}}
      TF_VAR_database_name: ${{secrets.TF_VAR_DATABASE_NAME}}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt
        
      - name: Terraform Plan
        run: terraform plan 
        
      - name: Prep tests
        run: |
          terraform plan -out tfplan.binary
          terraform show -json tfplan.binary > tfplan.json
          ls
          echo $PWD
          
      #- name: OPA tests 2
      #  uses: ibiqlik/conftest-action-docker@master
      #  with:
      #    path: "examples/account.json"
      #    policy: "policy"
      - name: OPA tests
        uses: ibiqlik/conftest-action-docker@master
        with:
          path: "src/terraform/tfplan.json"
          policy: "policy"

  awsterraform:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@master
      ## Leaving terraform cmds as example but not run due to credential requirements
      # - name: Terraform plan
      #   run: |
      #     cd examples/aws/public_s3/
      #     terraform init
      #     terraform plan -out public_s3.tfplan
      #     terraform show -json public_s3.tfplan > public_s3.json
      - name: OPA tests
        uses: ibiqlik/conftest-action-docker@v1
        with:
          path: "examples/public_s3.json"
          policy: "examples/policy"
